M48
; DRILL file KiCad 10.0.5 date 2026-08-27T04:36:11
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-27T04:36:11-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X165.11Y-36.605
X170.89Y-36.605
T2
X154.5Y-39.1
X154.5Y-45.9
M30
